# Live session /etc/bashrc

echo -e "\nWelcome to \e[34mAerynOS\e[0m!"
echo -e "\n"
echo -e "To install, run 'sudo lichen'. Note, you need to partition your disk first"

# End live session /etc/bashrc

